#!/usr/bin/env bash

function quality {
    ruff check --fix && ruff format
}

function check-quality {
    ruff check && ruff format --check
}

function test {
    docker build -f Dockerfile.test -t box-mock-test .
    docker run --rm -it -v "$(pwd):/app" box-mock-test
}

TIMEFORMAT=$'\nTask completed in %3lR'
time "${@:-help}"